### ISSUE TITLE
TM2020 Recap is not loading anything

### ISSUE THREAD

**Issue by twiikker** [drekdrek/grinding-stats#46]
If i go to recap it does not load anything and if i press refresh on either All tracks or other subsections i get these errors.

```
[   ScriptRuntime] [  LOG] [12:33:08] [GrindingStats]  Fetching campaign data
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]  Script exception: Json value is not a string!
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]    GrindingStats.op/:/src/Recap/RecapFiles.as (line 16, column 4)
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]      #0  void RecapFiles::load() (GrindingStats.op/:/src/Recap/RecapFiles.as line 16)
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]      #1  RecapFiles::RecapFiles(const string&in id) (GrindingStats.op/:/src/Recap/RecapFiles.as line 7)
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]      #2  RecapFiles@ RecapFiles(const string&in id) (GrindingStats.op/:/src/Recap/RecapFiles.as line 0)
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]      #3  RecapElement::RecapElement(const string&in id) (GrindingStats.op/:/src/Recap/RecapElement.as line 26)
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]      #4  RecapElement@ RecapElement(const string&in id) (GrindingStats.op/:/src/Recap/RecapElement.as line 0)
[   ScriptRuntime] [ERROR] [12:33:09] [GrindingStats]      #5  void Recap::load_files() (GrindingStats.op/:/src/Recap/Recap.as line 197)
```

**Comment by nikarmotte** [comment]
Hi, this has already been reported on the Openplanet discord server in the [Grinding Stats channel](https://discord.com/channels/276076890714800129/1047245343923900437/1290802772827967500).

This has actually already been fixed in the [last commit](https://github.com/drekdrek/grinding-stats/commit/2a26879fa8e6a8a9f55c4ec0a6b74eea4ca23d79).

We just need to wait until the author makes a new release.

As far as I understand, if you really really want to see you stats now, you could temporarily move your files outside your data folder until the fix is released.
There is also another fix for the 500 tracks limit, in case you also hit that one.

I hope it helps.
